"""add created_at to study_records

Revision ID: 2b2f6873e976
Revises: 16165faf8b31
Create Date: 2026-06-12 20:11:14.584892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2f6873e976'
down_revision: Union[str, Sequence[str], None] = '16165faf8b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study_records",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_records', 'created_at')
    # ### end Alembic commands ###
